### ISSUE TITLE
Access FancyMenu config instance instead of creating new instance

### ISSUE THREAD

**Issue by Keksuccino** [ixDarkLorD/ModpackManager#1]
Hi!

Just saw that you're creating a new config instance to change a value in FancyMenu's config, which can cause problems:
https://github.com/ixDarkLorD/ModpackManager/blob/a9189d89c568f25cfc9e5beea27b6cf8f2aee2f7/Common/src/main/java/net/ixdarklord/packmger/compat/fancymenu/FancyMenuRegistry.java#L23

You should instead access the real config instance of FancyMenu:
https://github.com/Keksuccino/FancyMenu/blob/b82cf57fa4e80ad4c642ae616caabae2ebd0e4cd/src/main/java/de/keksuccino/fancymenu/FancyMenu.java#L63

Thank you! :)

**Comment by ixDarkLorD** [comment]
Hi @Keksuccino 😊👋
I didn't notice that I could access the config immediately from FancyMenu class. **It will be implemented in the next update!**
Thank you for mentioning this! I appreciate it ❤️

**Comment by Keksuccino** [comment]
Some off-topic stuff:

Hey again! Well, sorry for abusing this issue (I should know better lmao), but I found your mod because one of my users told me about it (they thought it's copying FM, because of the screenshots, but I later realized you're just adding new stuff via the FM APIs).

Soo I have a question: Are you planning to kinda make a replacement for FancyMenu, Drippy and Spiffy or do you plan to extend it?
I'm asking because of your "planned features" list on CurseForge :D
(Just asking out of curiosity and because it would be cool to finally have a mod that actually tries to extend FancyMenu with new features and stuff)

**Comment by ixDarkLorD** [comment]
Feel free to reach out to me anytime!
I'm glad that you asked. @Keksuccino❤️

No! I've never thought I would make a replacement for FancyMenu because it's already perfect! My planned feature list is kinda misleading, to be honest. xD (I should've explained it or written it better)
My initial idea is to create a mod that makes some things easier for modpack creators! It begins with an update checker.

And later, I included FancyMenu API to make it even better for the users! If they use FancyMenu along with my mod, They will have the same features in FancyMenu as an extended add-on.

I planned to make the same thing with Drippy and Spiffy if possible!
I Really, really enjoyed using your mod! It's one of the best!

**Comment by Keksuccino** [comment]
Oh that sounds great!

But I wouldn't try to do anything with Spiffy tbh.. I don't plan to release more updates for it and if I do, then it will be a complete rewrite :D So please don't waste your time with it.

And if you plan to add more placeholders to FM, wait a bit. Like 3 weeks or so, until the new update is public, because I completely replaced the old system with a rewrite. Has better value support, nested placeholder support, etc. :D

Oh and thank you very much for your kind words!
